### ISSUE TITLE
请教大佬如何在自己的数据集上调参数

### ISSUE THREAD

**Issue by PriceZhang** [ZF1044404254/MMAL-Net#22]
大佬，我用您的代码集中跑战斗机的数据，（战斗机数据像素大小约为300*300，共16个类别，每个类约300张图片），调整了下input_size，stride，window_sized，但是都是盲目去调的，效果都不太好，最终的最好训练结果在60%左右，请大佬指导一下参数的调整方向，感谢！

**Comment by ZF1044404254** [comment]
你好，请问你有试过不调整这些超参数的进行训练嘛，效果如何？

**Comment by PriceZhang** [comment]
嗯嗯，用原始参数训了100轮，最好效果是68%左右，然后后边开始趋于平稳了

**Comment by ZF1044404254** [comment]
请问直接用resnet等网络训练能达到什么水平？你的数据集中每张图像中一般有多少战斗机的吗？

**Comment by PriceZhang** [comment]
> 请问直接用resnet等网络训练能达到什么水平？你的数据集中每张图像中一般有多少战斗机的吗？

嗯……我没用resnet直接训，可能是bg类的原因，去掉了bg类，准确率跑到了80%。但是预测的效果不好，我还在找原因。多谢大佬回复

**Comment by fuyimin96** [comment]
> 大佬，我用您的代码集中跑战斗机的数据，（战斗机数据像素大小约为300*300，共16个类别，每个类约300张图片），调整了下input_size，stride，window_sized，但是都是盲目去调的，效果都不太好，最终的最好训练结果在60%左右，请大佬指导一下参数的调整方向，感谢！

请问方便分享下战斗机的数据集吗
