### ISSUE TITLE
三个分支是共享权重的？

### ISSUE THREAD

**Issue by zyccccc** [ZF1044404254/MMAL-Net#5]

**Comment by ZF1044404254** [comment]
是的


 
---原始邮件---
发件人: "zyccccc"<notifications@github.com&gt;
发送时间: 2020年5月18日 20:03:15
收件人: "ZF1044404254/TBMSL-Net"<TBMSL-Net@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZF1044404254/TBMSL-Net] 三个分支是共享权重的？ (#5)

**Comment by zyccccc** [comment]
谢谢 ，请问如果不同尺度的放入不同的cnn这样会有提高吗？

**Comment by ZF1044404254** [comment]
没有尝试过，因为那样太耗费显存了。
